dist: xenial
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
language: node_js
node_js:
  - 10
  - 12
  - 13
branches:
  only:
    - master
after_success: npm run coverage
